### PR TITLE
[BUGFIX] Change storage_pid TCA to work with MySQL strict mode

### PR DESCRIPTION
**Pull request by sypets**
Description is in this issue: https://github.com/FriendsOfTYPO3/compatibility6/issues/18

### CODE REVIEW

**Comment by IchHabRecht** [comment]
Hi @sypets,

I had a look into the default core TCA configurations, fe_groups and even tt_content). Would you mind to explain the problem you have without that patch applied in your system?

Thank you very much.

**Comment by IchHabRecht** [comment]
Hi @sypets,

I found your ticket and will investigate what the problem is.

**Comment by IchHabRecht** [comment]
Never mind, I found the problem.

Travis: https://travis-ci.org/FriendsOfTYPO3/compatibility6/builds/306076564

**Comment by sypets** [comment]
Sorry for not responding right away. It's been a while since I created this PR. I now added a description with a link to the issue just for clarification. 

Thanks for taking care of this!

**Pull request merged**
